[build-system]
<<<<<<< HEAD
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
=======
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
>>>>>>> cdc42936f83c2f0aba3cc6f07367ab6063b26bb0
